#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

source=~/.config/hypr/look-and-feel/general.conf
source=~/.config/hypr/look-and-feel/decoration.conf
source=~/.config/hypr/look-and-feel/animation.conf
source=~/.config/hypr/look-and-feel/dwindle.conf
source=~/.config/hypr/look-and-feel/master.conf
source=~/.config/hypr/look-and-feel/misc.conf
