bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = ALT_SHIFT, F, togglefloating,
bind = $mainMod, SPACE, exec, $menu
# bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, layoutmsg, togglesplit # dwindle

$vs_code_arrows = ~/.config/hypr/keybindings/scripts/vs-code-arrows.sh
# Move focus with mainMod + arrow keys
bind = $mainMod, left, exec, $vs_code_arrows left
bind = $mainMod, right, exec, $vs_code_arrows right
bind = $mainMod, up, exec, $vs_code_arrows up
bind = $mainMod, down, exec, $vs_code_arrows down
#

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
