monitor=,preferred,auto,auto

$terminal = kitty
$fileManager = yazi
$menu = fuzzel

source = exec-once.conf
source = env.conf
source = look-and-feel/index.conf
source = input/index.conf
source = keybindings/index.conf
source = window-and-workspaces.conf

