$script = ~/.config/hypr/keybindings/scripts/standard-mac.sh

bind = $mainMod, C, exec, $script c
bind = $mainMod, V, exec, $script v
bind = $mainMod, S, exec, $script s
bind = $mainMod, A, exec, $script a

bind = SUPER SHIFT, left, exec, $script super_left
bind = SUPER SHIFT, right, exec, $script super_right
bind = ALT SHIFT, left, exec, $script shift_left
bind = ALT SHIFT, right, exec, $script shift_right

