monitor=,preferred,auto,auto

$terminal = ~/.config/hypr/keybindings/scripts/firefox-alt-t.sh
$fileManager = thunar
$menu = fuzzel
$videoRecorder = kooha

source = exec-once.conf
source = env.conf
source = look-and-feel/index.conf
source = input/index.conf
source = keybindings/index.conf
source = window-and-workspaces.conf

